eiffel-community/etos-library

- requirements.txt
- setup.cfg
- src/etos_lib/etos.py
- src/etos_lib/lib/config.py
N/A
Update to latest eiffellib and set routing_key to None.
Also add an optional domain_id to constructor.
This change cannot be merged until eiffel-community/eiffel-pythonlib#37 is merged
Eiffellib updated, we should always follow eiffellib. No other alternative was considered.
This change adds routing keys to events.
None
work with modifications, whether …
> Set routing key to None in eiffellib

- src/etos_lib/lib/debug.py
- src/etos_lib/lib/events.py
fixes: eiffel-community/etos#88
Added the ability to set which tag to use in routing keys for events sent in ETOS.
I added the parameter to the debug module which is deprecated, but it is still the best place for these variables in order to follow a common structure.
I decided against adding all of the parameters in a routing key since I feel that the "tag" is the only field that we want to modify
This change allows us to run ETOS development in a production environment by separating out the routing keys for each deployment.
Can be unclear why suite starter did not trigger if routing key tags are set
have the right to submit it …
> Add ability to set routing key tag via environment variables

- .gitignore
- requirements.txt
- setup.cfg
- src/etos_lib/lib/config.py
- src/etos_lib/logging/log_publisher.py
- src/etos_lib/logging/logger.py
- src/etos_lib/logging/rabbitmq_handler.py
based on #18 
eiffel-community/etos#148
Add so that the ETOS library will send logs to another RabbitMQ exchange for other services to consume.
I made it so that the new RabbitMQ exchange is required. This is because we want ETOS client to rely on this information in order to print more user-focused information.
This will allow ETOS to communicate back user logs to the ETOS client in a structured way.
Possible flakiness due to using another RabbitMQ publisher in all ETOS services, but we are using the eiffellib RabbitMQ publisher design which is extremely stable so I don't see this as a major problem.
have the right to submit it …
> Rabbitmq logging

- src/etos_lib/lib/debug.py
- src/etos_lib/logging/logger.py
Based on: #20 
Some services, like the ETOS API, do not benefit from sending logs to RabbitMQ as they are run too early for the ESR to pick them up.
We did have the "disable_sending_events" flag before, but some services do still need to publish events while not publishing logs so this added flag will allow for that.
Services that require the sending of events but not logs can control the flow.
None
license and I have the …
> Disable sending logs

- src/etos_lib/lib/debug.py
None
Set the default to true when sending logs to RabbitMQ
The current design where the default is False works pretty well when upgrading ETOS Library to services that don't need to send logs to RabbitMQ, but the problem is that we are going to design ETOS to work with these logs by default so having the default be False just does not make sense.
I had too much tunnelvision in #21  to see this.
This will enable the log sending on all services by default
This will enable the log sending on all services by default, even those that don't need it. They will need to disable it by setting "ETOS_ENABLE_SENDING_LOGS=false"
have the right …
> Set default log sending to true

- src/etos_lib/logging/logger.py
None
Prevent deadlocks when using the rabbitmq logger. The problem was that we had the wrong name when disabling propagation.
I tried to fix the rabbitmq logging handler so that it does not have a problem when the rabbitmq publisher sends logs to it, but I was not able to find a good enough solution that worked.
ETOS works again.
None
work with modifications, …
> Prevent deadlocks in rabbitmq logging

- src/etos_lib/lib/http.py
None
The old implementation is too inflexible and causes a lot of headaches. With this new one we will only retry on certain errors and exit early otherwise.
The new system is also much more configurable with the use of urllib3 Retry helper so that each component can decide on their own retry strategy.
I thought about just letting each service decide on their own as the duplicated code is not that massive. However with the way this implementation works I am not afraid that we'll get into the same situation that we have now.
Allows us to exit early if there are unrecoverable errors and also allows the applications to decide themselves how their retry strategies should be.
This is not a backwards-compatible change. Decided against adding deprecated versions of the old methods since it would …
> Replace the wait_for functionality in lib/http

- docs/conf.py
- pylintrc
- requirements.txt
- setup.cfg
- src/etos_lib/eiffel/__init__.py
- src/etos_lib/eiffel/common.py
- src/etos_lib/eiffel/publisher.py
- src/etos_lib/eiffel/subscriber.py
- src/etos_lib/etos.py
- src/etos_lib/kubernetes/base.py
- src/etos_lib/kubernetes/jobs.py
- src/etos_lib/lib/debug.py
- src/etos_lib/lib/events.py
- src/etos_lib/lib/utils.py
- src/etos_lib/logging/formatter.py
- src/etos_lib/logging/log_publisher.py
- src/etos_lib/logging/logger.py
- tox.ini
eiffel-community/etos#204
Add automatic tracing support to ETOS events. This change overrides the RabbitMQPublisher and Subscriber from the Eiffellib and forcefully adds information as well as injecting a trace context to the header of the AMQ packet.
I looked at using the pika auto instrumentation library that's available, sadly that one only works for BlockingConnections (we use SelectConnection). Obviously I could update the auto instrumentation but that felt like a much bigger job than what I did here.
We could also add this to the eiffellib directly. We decided against this since we kinda want to create an SDK for python instead of relying on the library and maybe move over most RabbitMQ parts to ETOS Library (this depends on what the Eiffel community wants, but we could maintain …
> Add tracing

- src/etos_lib/eiffel/common.py
This change fixes the return typehint in the _flatten() function in common.py.
(c) The contribution was provided directly to me by some other
person who certified (a), …
> fix return type in common.py:_flatten()

- src/etos_lib/opentelemetry/__init__.py
- src/etos_lib/opentelemetry/semconv.py
- https://github.com/eiffel-community/etos/issues/228
This change adds OpenTelemetry attribute names as a definition of ETOS-specific semantic conventions. 
(c) The …
> Add consts for OpenTelemetry semantic conventions

- src/etos_lib/logging/filter.py
- https://github.com/eiffel-community/etos/issues/236
This change adds OpenTelemetry trace id to logstash entries.
(c) The contribution was provided directly to me by …
> Add OpenTelemetry trace id to Logstash entries

- src/etos_lib/logging/filter.py
- https://github.com/eiffel-community/etos/issues/236
Currently OpenTelemetry trace id is returned as an integer converted to string. It needs to be a hex string instead. …
> OpenTelemetry trace id for logstash in hex format

- src/etos_lib/logging/logger.py
- https://github.com/eiffel-community/etos/issues/247
This change prevents log propagation from eiffel.publisher.TracingRabbitMQPublisher in RabbitMQLogPublisher to avoid the deadlock condition described in the issue above.
permitted to submit …
> Disable eiffel.publisher.* for RabbitMQLogPublisher

- setup.cfg
- https://github.com/eiffel-community/etos/issues/248
This change updates pyscaffold to >=4.5 and fixes several deprecation warnings in setup.cfg.
(c) The contribution …
> pyscaffold update and setup.cfg fixes

- setup.py
- https://github.com/eiffel-community/etos/issues/248
This version fixes the retrieval of version from Git when the commit is not on the release branch. The Git branch is now used only to determine if the tag shall have a "dev" or "post" suffix when the commit is untagged.
by me, under the same open …
> Fix setuptools_scm version retrieval from detached HEAD

- pyproject.toml
- setup.py
- src/etos_lib/eiffel/common.py
- src/etos_lib/lib/utils.py
- https://github.com/eiffel-community/etos/issues/284
This change fixes the compatibility problem with tox/setuptools by moving the options from `pyproject.toml` to `setup.py`.
in the …
> Compatibility fix for latest tox and setuptools

- pyproject.toml
- src/etos_lib/kubernetes/__init__.py
- src/etos_lib/kubernetes/environment.py
- src/etos_lib/kubernetes/environment_request.py
- src/etos_lib/kubernetes/etos.py
- src/etos_lib/kubernetes/provider.py
- src/etos_lib/kubernetes/schemas/__init__.py
- src/etos_lib/kubernetes/schemas/common.py
- src/etos_lib/kubernetes/schemas/environment.py
- src/etos_lib/kubernetes/schemas/environment_request.py
- src/etos_lib/kubernetes/schemas/provider.py
- src/etos_lib/kubernetes/schemas/testrun.py
- src/etos_lib/kubernetes/testrun.py
eiffel-community/etos#242
Added schemas and helper methods for interacting with ETOS kubernetes resources.
I had these helpers in each service before, but that cause so much friction any time the packages changed as I needed to update every single one and make the correct change. While we still have to update every service when the library updates, at least we don't have to make the same code change multiple times.
Explained briefly in Alternate Designs.
of my knowledge, is covered …
> Add Kubernetes CRD client and schemas

- src/etos_lib/kubernetes/etos.py
eiffel-community/etos-suite-runner#67
If initializing the Kubernetes client outside of Kubernetes then it would crash due to not being able to communicate with expected endpoints. We should be allowed to initialize the client in tests.
permitted …
> Load client lazily

- pyproject.toml
- src/etos_lib/logging/log_processors.py
- src/etos_lib/logging/logger.py
Introduce setup for OpenTelemetry logging, including necessary dependencies and custom log processors to enhance logging capabilities.
OpenTelemetry logging signals for Python is still very much in development anv new version are realease quite often, and sometimes things break. This can however bea easily mitigated with more carefull testing.
work with …
> Add OpenTelemetry logging setup

- src/etos_lib/logging/filter.py
- src/etos_lib/logging/logger.py
All the ETOS service currently implement a kind of broken logic to determine what environment (Development, (staging) and Production) that the specific service is running in. This logic does not take into account the possibility of one or several staging environments, this then bleeds into the logging setup and can interfere with telemetry logging signals, and thus by removing the expicit enviromnent requirement in EtosFilter we mitigate potential telemetry interference. We retain the parameter to the setup_logging function as a way to keep etos-library backwards compatible.
We could create a specific filter to use with specific telemetry logging signals but the generic logic to know which to use when might get tricky in the long run.
Logs no longer have the envronment record available on …
> Remove environment record form the ETOS logging filter
